-- require("one_monokai").setup({
--     transparent = true,  -- enable transparent window
--     colors = {},
--   --   themes = function(colors)
-- 		-- return{}
--   --   end,
--     italics = true, -- disable italics
-- })
