general.import = [
    "~/.config/alacritty/themed/themes/dark_pride.toml"
]
[env]
TERM = "alacritty"

[font]
size = 13.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift|Super"

[window]
opacity = 0.0
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 60
lines = 20
